# Generated by Django 5.0.2 on 2024-03-17 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('short_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('original_cost', models.FloatField()),
                ('discount_percentage', models.FloatField()),
                ('delivery_charges', models.FloatField()),
                ('making_charges', models.FloatField()),
                ('is_machine_made', models.BooleanField(default=False)),
                ('origin_country', models.CharField(max_length=50)),
                ('seller_address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProdutGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='product_gallery_store')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mart.product')),
            ],
        ),
    ]
